version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:pass@db:5432/market_db
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SECRET_KEY=your-secret-key-here
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./models
        target: /app/models
      - type: bind
        source: ./data
        target: /app/data

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=market_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d market_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 